### ISSUE TITLE
CSS conflicting with colorpicker component

### ISSUE THREAD

**Issue by noquierouser** [origgami/CMB2-grid#21]
Loading CMB2 Grid conflicts with colorpicker CSS. Probably related to box-sizing attribute.

Before clicking colorpicker
![01](https://cloud.githubusercontent.com/assets/463168/15128673/9ceeed02-1613-11e6-87aa-1e20bf59a0f3.PNG)

After clicking colorpicker
![02](https://cloud.githubusercontent.com/assets/463168/15128681/a9087504-1613-11e6-8cde-5ddcb6a767b7.PNG)

**Comment by noquierouser** [comment]
I found out the issue is originated in the Bootstrap CSS contained in the plugin.

``` css
.postbox-container .cmb2-wrap *, .postbox-container .cmb2-wrap {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

The way to fix this issue, at least how I managed to workaround this issue, is by enqueuing this CSS:

``` css
.wp-picker-holder * {
  box-sizing: content-box !important;
}
```

And setting it as dependant from CMB2 and CMB2 Grid styles:

``` php
wp_enqueue_style(
  'colorpicker_fix',
  plugins_url('lib/fix-cmb2-colorpicker-box-sizing.css', __FILE__),
  array('cmb2-styles', 'cmb2_grid_bootstrap_light') // here we set its dependencies
);
```
